/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.analysis;

import cordelmaisum.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTA(TA node);
    void caseTFuncao(TFuncao node);
    void caseTArruma(TArruma node);
    void caseTSe(TSe node);
    void caseTPara(TPara node);
    void caseTEla(TEla node);
    void caseTVoce(TVoce node);
    void caseTArranjar(TArranjar node);
    void caseTO(TO node);
    void caseTValor(TValor node);
    void caseTDe(TDe node);
    void caseTIra(TIra node);
    void caseTTe(TTe node);
    void caseTRetornar(TRetornar node);
    void caseTCom(TCom node);
    void caseTSua(TSua node);
    void caseTLicenca(TLicenca node);
    void caseTPor(TPor node);
    void caseTAqui(TAqui node);
    void caseTVamos(TVamos node);
    void caseTComecar(TComecar node);
    void caseTEm(TEm node);
    void caseTTroca(TTroca node);
    void caseTJa(TJa node);
    void caseTIa(TIa node);
    void caseTEsquecendo(TEsquecendo node);
    void caseTPreste(TPreste node);
    void caseTAtencao(TAtencao node);
    void caseTFavor(TFavor node);
    void caseTDiz(TDiz node);
    void caseTSer(TSer node);
    void caseTQue(TQue node);
    void caseTTem(TTem node);
    void caseTComo(TComo node);
    void caseTSeMini(TSeMini node);
    void caseTEntao(TEntao node);
    void caseTSenao(TSenao node);
    void caseTCondicao(TCondicao node);
    void caseTAssim(TAssim node);
    void caseTE(TE node);
    void caseTOu(TOu node);
    void caseTUm(TUm node);
    void caseTUma(TUma node);
    void caseTNumero(TNumero node);
    void caseTResposta(TResposta node);
    void caseTNada(TNada node);
    void caseTReticencias(TReticencias node);
    void caseTPonto(TPonto node);
    void caseTVirgula(TVirgula node);
    void caseTExclamacao(TExclamacao node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTSim(TSim node);
    void caseTNao(TNao node);
    void caseTNumeral(TNumeral node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMulti(TMulti node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTMaiorIgualQue(TMaiorIgualQue node);
    void caseTMenorIgualQue(TMenorIgualQue node);
    void caseTMaiorQue(TMaiorQue node);
    void caseTMenorQue(TMenorQue node);
    void caseTIgual(TIgual node);
    void caseTParenteseEsquerdo(TParenteseEsquerdo node);
    void caseTParenteseDireito(TParenteseDireito node);
    void caseTColcheteEsquerdo(TColcheteEsquerdo node);
    void caseTColcheteDireito(TColcheteDireito node);
    void caseTPipe(TPipe node);
    void caseTId(TId node);
    void caseTVazio(TVazio node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
