/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TReticencias extends Token
{
    public TReticencias()
    {
        super.setText("...");
    }

    public TReticencias(int line, int pos)
    {
        super.setText("...");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReticencias(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReticencias(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReticencias text.");
    }
}
